# Generated by Django 3.1.7 on 2021-04-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identityType',
            field=models.CharField(choices=[('nin', 'nin'), ('voters_card', 'voters_card'), ('drivers_license', 'drivers_license'), ('international_passport', 'international_passport')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_availability',
            field=models.CharField(choices=[('in_stock', 'in_stock'), ('out_of_stock', 'out_of_stock')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition',
            field=models.CharField(choices=[('dried', 'dried'), ('fresh', 'fresh'), ('new', 'new'), ('used', 'used'), ('refurbished', 'refurbished')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('not_rated', 'not_rated'), ('one_star', 'one_star'), ('two_star', 'two_star'), ('three_star', 'three_star'), ('four_star', 'four_star'), ('five_star', 'five_star')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='businessEntity',
            field=models.CharField(choices=[('individual', 'individual'), ('company', 'company')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='identityType',
            field=models.CharField(choices=[('nin', 'nin'), ('voters_card', 'voters_card'), ('drivers_license', 'drivers_license'), ('international_passport', 'international_passport')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='numberOfEmployee',
            field=models.CharField(choices=[('one_three', 'one_three'), ('four_eleven', 'four_eleven'), ('twelve_hundred', 'twelve_hundred'), ('hundred_above', 'hundred_above')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'bank_transfer'), ('cheque', 'cheque'), ('american_express', 'american_express'), ('master_card', 'master_card'), ('verve', 'verve'), ('paypal', 'paypal')], max_length=50, null=True),
        ),
    ]
